modLoader="javafml"
loaderVersion="[40,)"

license="All rights reserved"

[[mods]]
modId="robotics"
version="${file.jarVersion}"

displayName="Create Robotics"
logoFile="icon.png"

authors="WORKERT, OutCraft" 

description='''
Create Robotics is a mod about Robots and Robotics Automation in Minecraft using the Create mod.
Robots have many uses, some help you at specific tasks, some automate your factory and some fight your enemies.
Create Robotics has also a system planned for you to build and code your own robots.
'''


[[dependencies.outclient]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.outclient]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
