name: Build mod on push and send to Discord

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v3

      - name: Get branch name
        id: get_branch
        run: echo "branch=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@9aa31f26bc8e536d1faf4b332bb8365350743a18

      - name: Build jar
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Send building message to discord
        uses: realRobotix/action-discord-notifier@release-master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message-title: Building mod from branch ${{ steps.get_branch.outputs.branch }}

      - name: Send built file to discord
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ./build/libs/*.*
